IMAGE_SIZE = 48
NUM_CLASSES = 3
LABELS = ['NOT_NUDE','NUDE','UNKNOWN']
MODEL_SAVE_PATH = 'PLEASE ENTER THE MODEL_SAVE_PATH'#Example:/home/linux/Documents/NSFW_dataset/FINAL_SORT/Model/model8/NSFWmodel-8
VIDEO_SAVE_PATH = 'PLEASE ENTER THE VIDEO_SAVE_PATH'